app = "insightface-api"
primary_region = "iad"

[build]

[env]
NEW_RELIC_APP_NAME = "InsightFace API"
NEW_RELIC_ENVIRONMENT = "production"
NEW_RELIC_LOG = "stderr"
NEW_RELIC_LOG_LEVEL = "info"
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED = "true"
NEW_RELIC_CONFIG_FILE = "/app/newrelic.ini"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 5001
min_machines_running = 1
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "120s"
  interval = "30s"
  timeout = "10s"
  path = "/up"

[[vm]]
memory = "4gb"
size = "shared-cpu-8x"
